---
Organizations:
  - &CentralBankOrg
    Name: CentralBankOrg
    ID: CentralBankMSP
    MSPDir: crypto-config/ordererOrganizations/cbn.naijachain.org/msp

    Policies:
      Readers:
        Type: Signature
        Rule: "OR('CentralBankMSP.member')"
      Writers:
        Type: Signature
        Rule: "OR('CentralBankMSP.member')"
      Admins:
        Type: Signature
        Rule: "OR('CentralBankMSP.admin')"
      Endorsement:
        Type: Signature
        Rule: "OR('CentralBankMSP.peer')"

    OrdererEndpoints:
      - orderer.cbn.naijachain.org:7050

    AnchorPeers:
      - Host: peer0.cbn.naijachain.org
        Port: 11051

  - &AccessBankOrg
    Name: AccessBankMSP
    ID: AccessBankMSP
    MSPDir: crypto-config/peerOrganizations/accessbank.naijachain.org/msp

    Policies:
      Readers:
        Type: Signature
        Rule: "OR('AccessBankMSP.admin', 'AccessBankMSP.peer', 'AccessBankMSP.client')"
      Writers:
        Type: Signature
        Rule: "OR('AccessBankMSP.admin', 'AccessBankMSP.client')"
      Admins:
        Type: Signature
        Rule: "OR('AccessBankMSP.admin')"
      Endorsement:
        Type: Signature
        Rule: "OR('AccessBankMSP.peer')"

    AnchorPeers:
      - Host: peer0.accessbank.naijachain.org
        Port: 7051

  - &GTBankOrg
    Name: GTBankMSP
    ID: GTBankMSP
    MSPDir: crypto-config/peerOrganizations/gtbank.naijachain.org/msp

    Policies:
      Readers:
        Type: Signature
        Rule: "OR('GTBankMSP.admin', 'GTBankMSP.peer', 'GTBankMSP.client')"
      Writers:
        Type: Signature
        Rule: "OR('GTBankMSP.admin', 'GTBankMSP.client')"
      Admins:
        Type: Signature
        Rule: "OR('GTBankMSP.admin')"
      Endorsement:
        Type: Signature
        Rule: "OR('GTBankMSP.peer')"

    AnchorPeers:
      - Host: peer0.gtbank.naijachain.org
        Port: 8051

  - &ZenithBankOrg
    Name: ZenithBankMSP
    ID: ZenithBankMSP
    MSPDir: crypto-config/peerOrganizations/zenithbank.naijachain.org/msp

    Policies:
      Readers:
        Type: Signature
        Rule: "OR('ZenithBankMSP.admin', 'ZenithBankMSP.peer', 'ZenithBankMSP.client')"
      Writers:
        Type: Signature
        Rule: "OR('ZenithBankMSP.admin', 'ZenithBankMSP.client')"
      Admins:
        Type: Signature
        Rule: "OR('ZenithBankMSP.admin')"
      Endorsement:
        Type: Signature
        Rule: "OR('ZenithBankMSP.peer')"

    AnchorPeers:
      - Host: peer0.zenithbank.naijachain.org
        Port: 9051

  - &FirstBankOrg
    Name: FirstBankMSP
    ID: FirstBankMSP
    MSPDir: crypto-config/peerOrganizations/firstbank.naijachain.org/msp

    Policies:
      Readers:
        Type: Signature
        Rule: "OR('FirstBankMSP.admin', 'FirstBankMSP.peer', 'FirstBankMSP.client')"
      Writers:
        Type: Signature
        Rule: "OR('FirstBankMSP.admin', 'FirstBankMSP.client')"
      Admins:
        Type: Signature
        Rule: "OR('FirstBankMSP.admin')"
      Endorsement:
        Type: Signature
        Rule: "OR('FirstBankMSP.peer')"

    AnchorPeers:
      - Host: peer0.firstbank.naijachain.org
        Port: 10051

Capabilities:
  Channel: &ChannelCapabilities
    V2_0: true

  Orderer: &OrdererCapabilities
    V2_0: true

  Application: &ApplicationCapabilities
    V2_5: true

Application: &ApplicationDefaults
  Organizations:

  Policies:
    Readers:
      Type: ImplicitMeta
      Rule: "ANY Readers"
    Writers:
      Type: ImplicitMeta
      Rule: "ANY Writers"
    Admins:
      Type: ImplicitMeta
      Rule: "MAJORITY Admins"
    LifecycleEndorsement: # Chaincode Definition Approval
      Type: ImplicitMeta
      Rule: "MAJORITY Endorsement"
    Endorsement:
      Type: ImplicitMeta
      Rule: "MAJORITY Endorsement"

  Capabilities:
    <<: *ApplicationCapabilities

Orderer: &OrdererDefaults
  OrdererType: solo

  Addresses:
    - orderer.cbn.naijachain.org:7050

  BatchTimeout: 1s

  BatchSize:
    MaxMessageCount: 10
    AbsoluteMaxBytes: 99 MB
    PreferredMaxBytes: 512 KB

  EtcdRaft:
    Consenters:
      - Host: orderer.cbn.naijachain.org
        Port: 7050
        ClientTLSCert: crypto-config/ordererOrganizations/cbn.naijachain.org/orderers/orderer.cbn.naijachain.org/tls/server.crt
        ServerTLSCert: crypto-config/ordererOrganizations/cbn.naijachain.org/orderers/orderer.cbn.naijachain.org/tls/server.crt

  Organizations:
    - *CentralBankOrg

  Policies:
    Readers:
      Type: ImplicitMeta
      Rule: "ANY Readers"
    Writers:
      Type: ImplicitMeta
      Rule: "ANY Writers"
    Admins:
      Type: ImplicitMeta
      Rule: "MAJORITY Admins"
    BlockValidation:
      Type: ImplicitMeta
      Rule: "ANY Writers"

  Capabilities:
    <<: *OrdererCapabilities

Channel: &ChannelDefaults
  Policies:
    Readers:
      Type: ImplicitMeta
      Rule: "ANY Readers"
    Writers:
      Type: ImplicitMeta
      Rule: "ANY Writers"
    Admins:
      Type: ImplicitMeta
      Rule: "MAJORITY Admins"

  Capabilities:
    <<: *ChannelCapabilities

Profiles:
  NaijaBanksOrdererGenesis:
    <<: *ChannelDefaults
    Orderer:
      <<: *OrdererDefaults
      Organizations:
        - *CentralBankOrg
      Capabilities:
        <<: *OrdererCapabilities

    Consortiums:
      RetailConsortium:
        Organizations:
          - *AccessBankOrg
          - *GTBankOrg
          - *ZenithBankOrg
          - *FirstBankOrg
          - *CentralBankOrg

  RetailChannel:
    Consortium: RetailConsortium
    <<: *ChannelDefaults
    Application:
      <<: *ApplicationDefaults
      Organizations:
        - *AccessBankOrg
        - *GTBankOrg
        - *ZenithBankOrg
        - *FirstBankOrg
        - *CentralBankOrg
      Capabilities:
        <<: *ApplicationCapabilities
