OrdererOrgs:
  - Name: CentralBankOrg
    Domain: cbn.naijachain.org
    EnableNodeOUs: true
    Specs:
      - Hostname: orderer
        SANS:
          - "localhost"
          - "127.0.0.1"

PeerOrgs:
  - Name: CentralBankOrg # logical peer org name
    Domain: cbn.naijachain.org # shares the same domain
    EnableNodeOUs: true
    Template:
      Count: 1 # peer0.cbn.naijachain.org
      SANS:
        - "localhost"
    Users:
      Count: 1 # admin / user1 certificates

  - Name: AccessBankOrg
    Domain: accessbank.naijachain.org
    EnableNodeOUs: true
    Template:
      Count: 1
      SANS:
        - "localhost"
    Users:
      Count: 1

  - Name: GTBankOrg
    Domain: gtbank.naijachain.org
    EnableNodeOUs: true
    Template:
      Count: 1
      SANS:
        - "localhost"
    Users:
      Count: 1

  - Name: ZenithBankOrg
    Domain: zenithbank.naijachain.org
    EnableNodeOUs: true
    Template:
      Count: 1
      SANS:
        - "localhost"
    Users:
      Count: 1

  - Name: FirstBankOrg
    Domain: firstbank.naijachain.org
    EnableNodeOUs: true
    Template:
      Count: 1
      SANS:
        - "localhost"
    Users:
      Count: 1
