networks:
  retail:

services:
  orderer.cbn.naijachain.org:
    container_name: orderer.cbn.naijachain.org
    image: hyperledger/fabric-orderer:$IMAGE_TAG
    environment:
      - FABRIC_LOGGING_SPEC=DEBUG
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/genesis.block
      - ORDERER_GENERAL_LOCALMSPID=CentralBankMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      # enabled TLS
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_CLUSTER_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    ports:
      - 7050:7050
    volumes:
      - ./crypto-config/ordererOrganizations/cbn.naijachain.org/orderers/orderer.cbn.naijachain.org/msp:/var/hyperledger/orderer/msp
      - ./crypto-config/ordererOrganizations/cbn.naijachain.org/orderers/orderer.cbn.naijachain.org/tls/:/var/hyperledger/orderer/tls
      - ./channel-artifacts/genesis.block:/var/hyperledger/orderer/genesis.block
      - orderer.cbn.naijachain.org:/var/hyperledger/production/orderer
    networks:
      retail:
        aliases:
          - orderer.cbn.naijachain.org

  couchdb0:
    container_name: couchdb0
    image: hyperledger/fabric-couchdb
    platform: linux/amd64
    environment:
      - COUCHDB_USER=
      - COUCHDB_PASSWORD=
    ports:
      - 5984:5984
    networks:
      - retail

  couchdb1:
    container_name: couchdb1
    image: hyperledger/fabric-couchdb
    platform: linux/amd64
    environment:
      - COUCHDB_USER=
      - COUCHDB_PASSWORD=
    ports:
      - 6984:5984
    networks:
      - retail

  couchdb2:
    container_name: couchdb2
    image: hyperledger/fabric-couchdb
    platform: linux/amd64
    environment:
      - COUCHDB_USER=
      - COUCHDB_PASSWORD=
    ports:
      - 7984:5984
    networks:
      - retail

  couchdb3:
    container_name: couchdb3
    image: hyperledger/fabric-couchdb
    platform: linux/amd64
    environment:
      - COUCHDB_USER=
      - COUCHDB_PASSWORD=
    ports:
      - 8984:5984
    networks:
      - retail

  couchdb4:
    container_name: couchdb4
    image: hyperledger/fabric-couchdb
    platform: linux/amd64
    environment:
      - COUCHDB_USER=
      - COUCHDB_PASSWORD=
    ports:
      - 9984:5984
    networks:
      - retail

  peer0.cbn.naijachain.org:
    container_name: peer0.cbn.naijachain.org
    extends:
      file: base.yaml
      service: peer-base
    environment:
      # - CORE_PEER_PROFILE_ENABLED=true
      # Peer specific variabes
      - CORE_PEER_ID=peer0.cbn.naijachain.org
      - CORE_PEER_ADDRESS=peer0.cbn.naijachain.org:11051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:11051
      - CORE_PEER_CHAINCODEADDRESS=peer0.cbn.naijachain.org:11052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:11052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.cbn.naijachain.org:11051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.cbn.naijachain.org:11051
      - CORE_PEER_LOCALMSPID=CentralBankPeerMSP
      # - CORE_OPERATIONS_LISTENADDRESS=
      # State database
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb4:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=
    ports:
      - 11051:11051
      - 11053:11053
    volumes:
      - /var/run/docker.sock:/host/var/run/docker.sock
      - ./crypto-config/peerOrganizations/cbn.naijachain.org/peers/peer0.cbn.naijachain.org/msp:/etc/hyperledger/peer/msp
      - ./crypto-config/peerOrganizations/cbn.naijachain.org/peers/peer0.cbn.naijachain.org/tls/:/etc/hyperledger/peer/tls
      - peer0.cbn.naijachain.org:/var/hyperledger/production
    networks:
      retail:
        aliases:
          - peer0.cbn.naijachain.org
    depends_on:
      - orderer.cbn.naijachain.org
      - couchdb4

  peer0.accessbank.naijachain.org:
    container_name: peer0.accessbank.naijachain.org
    extends:
      file: base.yaml
      service: peer-base
    environment:
      # - CORE_PEER_PROFILE_ENABLED=true
      # Peer specific variabes
      - CORE_PEER_ID=peer0.accessbank.naijachain.org
      - CORE_PEER_ADDRESS=peer0.accessbank.naijachain.org:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=peer0.accessbank.naijachain.org:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.accessbank.naijachain.org:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.accessbank.naijachain.org:7051
      - CORE_PEER_LOCALMSPID=AccessBankMSP
      # - CORE_OPERATIONS_LISTENADDRESS=
      # State database
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb0:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=
    ports:
      - 7051:7051
      - 7053:7053
    volumes:
      - /var/run/docker.sock:/host/var/run/docker.sock
      - ./crypto-config/peerOrganizations/accessbank.naijachain.org/peers/peer0.accessbank.naijachain.org/msp:/etc/hyperledger/peer/msp
      - ./crypto-config/peerOrganizations/accessbank.naijachain.org/peers/peer0.accessbank.naijachain.org/tls/:/etc/hyperledger/peer/tls
      - peer0.accessbank.naijachain.org:/var/hyperledger/production
    networks:
      retail:
        aliases:
          - peer0.accessbank.naijachain.org
    depends_on:
      - peer0.cbn.naijachain.org
      - couchdb0

  peer0.gtbank.naijachain.org:
    container_name: peer0.gtbank.naijachain.org
    extends:
      file: base.yaml
      service: peer-base
    environment:
      # - CORE_PEER_PROFILE_ENABLED=true
      # Peer specific variabes
      - CORE_PEER_ID=peer0.gtbank.naijachain.org
      - CORE_PEER_ADDRESS=peer0.gtbank.naijachain.org:8051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:8051
      - CORE_PEER_CHAINCODEADDRESS=peer0.gtbank.naijachain.org:8052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:8052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.gtbank.naijachain.org:8051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.gtbank.naijachain.org:8051
      - CORE_PEER_LOCALMSPID=GTBankMSP
      # - CORE_OPERATIONS_LISTENADDRESS=
      # State database
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb1:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=
    ports:
      - 8051:8051
      - 8053:8053
    volumes:
      - /var/run/docker.sock:/host/var/run/docker.sock
      - ./crypto-config/peerOrganizations/gtbank.naijachain.org/peers/peer0.gtbank.naijachain.org/msp:/etc/hyperledger/peer/msp
      - ./crypto-config/peerOrganizations/gtbank.naijachain.org/peers/peer0.gtbank.naijachain.org/tls/:/etc/hyperledger/peer/tls
      - peer0.gtbank.naijachain.org:/var/hyperledger/production
    networks:
      retail:
        aliases:
          - peer0.gtbank.naijachain.org
    depends_on:
      - peer0.accessbank.naijachain.org
      - couchdb1

  peer0.zenithbank.naijachain.org:
    container_name: peer0.zenithbank.naijachain.org
    extends:
      file: base.yaml
      service: peer-base
    environment:
      # - CORE_PEER_PROFILE_ENABLED=true
      # Peer specific variabes
      - CORE_PEER_ID=peer0.zenithbank.naijachain.org
      - CORE_PEER_ADDRESS=peer0.zenithbank.naijachain.org:9051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:9051
      - CORE_PEER_CHAINCODEADDRESS=peer0.zenithbank.naijachain.org:9052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:9052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.zenithbank.naijachain.org:9051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.zenithbank.naijachain.org:9051
      - CORE_PEER_LOCALMSPID=ZenithBankMSP
      # - CORE_OPERATIONS_LISTENADDRESS=
      # State database
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb2:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=
    ports:
      - 9051:9051
      - 9053:9053
    volumes:
      - /var/run/docker.sock:/host/var/run/docker.sock
      - ./crypto-config/peerOrganizations/zenithbank.naijachain.org/peers/peer0.zenithbank.naijachain.org/msp:/etc/hyperledger/peer/msp
      - ./crypto-config/peerOrganizations/zenithbank.naijachain.org/peers/peer0.zenithbank.naijachain.org/tls/:/etc/hyperledger/peer/tls
      - peer0.zenithbank.naijachain.org:/var/hyperledger/production
    networks:
      retail:
        aliases:
          - peer0.zenithbank.naijachain.org
    depends_on:
      - peer0.gtbank.naijachain.org
      - couchdb2

  peer0.firstbank.naijachain.org:
    container_name: peer0.firstbank.naijachain.org
    extends:
      file: base.yaml
      service: peer-base
    environment:
      # - CORE_PEER_PROFILE_ENABLED=true
      # Peer specific variabes
      - CORE_PEER_ID=peer0.firstbank.naijachain.org
      - CORE_PEER_ADDRESS=peer0.firstbank.naijachain.org:10051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:10051
      - CORE_PEER_CHAINCODEADDRESS=peer0.firstbank.naijachain.org:10052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:10052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.firstbank.naijachain.org:10051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.firstbank.naijachain.org:10051
      - CORE_PEER_GOSSIP_USELEADERELECTION=false
      - CORE_PEER_GOSSIP_ORGLEADER=true
      - CORE_PEER_LOCALMSPID=FirstBankMSP
      # - CORE_OPERATIONS_LISTENADDRESS=
      # State database
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb3:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=
    ports:
      - 10051:10051
      - 10053:10053
    volumes:
      - /var/run/docker.sock:/host/var/run/docker.sock
      - ./crypto-config/peerOrganizations/firstbank.naijachain.org/peers/peer0.firstbank.naijachain.org/msp:/etc/hyperledger/peer/msp
      - ./crypto-config/peerOrganizations/firstbank.naijachain.org/peers/peer0.firstbank.naijachain.org/tls/:/etc/hyperledger/peer/tls
      - peer0.firstbank.naijachain.org:/var/hyperledger/production
    networks:
      retail:
        aliases:
          - peer0.firstbank.naijachain.org
    depends_on:
      - peer0.zenithbank.naijachain.org
      - couchdb3

volumes:
  orderer.cbn.naijachain.org:
  peer0.accessbank.naijachain.org:
  peer0.gtbank.naijachain.org:
  peer0.zenithbank.naijachain.org:
  peer0.firstbank.naijachain.org:
  peer0.cbn.naijachain.org: