# Definition of nodes
# addr address for node
# tls_ca_cert tls cert
# crypto-config/peerOrganizations/accessbank.naijachain.org/msp/tlscacerts/tlsca.accessbank.naijachain.org-cert.pem
peer1: &peer1
  addr: localhost:7051
  ssl_target_name_override: peer0.accessbank.naijachain.org
  org: accessbank.naijachain.org
  tls_ca_cert: ../crypto-config/peerOrganizations/accessbank.naijachain.org/msp/tlscacerts/tlsca.accessbank.naijachain.org-cert.pem

peer2: &peer2
  addr: localhost:8051
  ssl_target_name_override: peer0.gtbank.naijachain.org
  org: gtbank.naijachain.org
  tls_ca_cert: ../crypto-config/peerOrganizations/gtbank.naijachain.org/msp/tlscacerts/tlsca.gtbank.naijachain.org-cert.pem

peer3: &peer3
  addr: localhost:9051
  ssl_target_name_override: peer0.zenithbank.naijachain.org
  org: zenithbank.naijachain.org
  tls_ca_cert: ../crypto-config/peerOrganizations/zenithbank.naijachain.org/msp/tlscacerts/tlsca.zenithbank.naijachain.org-cert.pem

peer4: &peer4
  addr: localhost:10051
  ssl_target_name_override: peer0.firstbank.naijachain.org
  org: firstbank.naijachain.org
  tls_ca_cert: ../crypto-config/peerOrganizations/firstbank.naijachain.org/msp/tlscacerts/tlsca.firstbank.naijachain.org-cert.pem

peer5: &peer5
  addr: localhost:11051
  ssl_target_name_override: peer0.cbn.naijachain.org
  org: cbn.naijachain.org
  tls_ca_cert: ../crypto-config/peerOrganizations/cbn.naijachain.org/msp/tlscacerts/tlsca.cbn.naijachain.org-cert.pem

orderer1: &orderer1
  addr: localhost:7050
  ssl_target_name_override: orderer.cbn.naijachain.org
  org: cbn.naijachain.org
  tls_ca_cert: ../crypto-config/ordererOrganizations/cbn.naijachain.org/msp/tlscacerts/tlsca.cbn.naijachain.org-cert.pem

# Peer Nodes to interact with as endorsement Peers
endorsers:
  - *peer1
  - *peer2
  - *peer3
  - *peer4
  - *peer5

# Peer Nodes to interact with as Commit Peers as listening
committers:
  - *peer1
  - *peer2
  - *peer3
  - *peer4
  - *peer5
# we might support multi-committer in the future for more complex test scenario.
# i.e. consider tx committed only if it's done on >50% of nodes.
# Give your commit Threshold as numbers for peers here.
commitThreshold: 2

# orderer Nodes to interact with
orderer: *orderer1

# Invocation configs
channel: retailchannel
chaincode: account
# chain code args below, in a list of str
# we provides 3 kinds of randmon
# uuid
# randomString$length
# randomNumber$min_$max
args:
  - GetBankAccountBalance
  # - uuid
  # - randomString8
  # - randomNumber0_50
  # - randomString8
  # - randomNumber0_50
# Tx submiter information
mspid: AccessBankMSP
private_key: ../crypto-config/peerOrganizations/accessbank.naijachain.org/users/User1@accessbank.naijachain.org/msp/keystore/priv_sk
sign_cert: ../crypto-config/peerOrganizations/accessbank.naijachain.org/users/User1@accessbank.naijachain.org/msp/signcerts/User1@accessbank.naijachain.org-cert.pem
# network traffic control
num_of_conn: 1 # number of gRPC connections to each peer/orderer
client_per_conn: 1 # clients per connection sending envelopes
policyFile: ./andLogic.rego

